# Generated by Django 5.0.3 on 2024-04-14 12:24

import django.utils.timezone
import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Posts",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        max_length=255, verbose_name="Заголовок поста"
                    ),
                ),
                (
                    "img",
                    models.ImageField(
                        default="/svg/no_image_avaliable.svg",
                        upload_to="photos/%Y/%m/%d/",
                        verbose_name="Фото",
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        max_length=255, unique=True, verbose_name="URL"
                    ),
                ),
                ("karma", models.IntegerField(default=0, verbose_name="Карма")),
                (
                    "published_time",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        verbose_name="Время публикации",
                    ),
                ),
                (
                    "content",
                    tinymce.models.HTMLField(verbose_name="Содержание статьи"),
                ),
            ],
            options={
                "verbose_name": "Посты",
                "verbose_name_plural": "Посты",
                "ordering": ["-published_time"],
            },
        ),
    ]
