# Generated by Django 5.0.3 on 2024-04-22 17:58

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0003_remove_posts_karma_posts_dislike_posts_like"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="posts",
            name="dislike",
            field=models.ManyToManyField(
                related_name="dislikes",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Дизлайки",
            ),
        ),
        migrations.AlterField(
            model_name="posts",
            name="like",
            field=models.ManyToManyField(
                related_name="likes",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Лайки",
            ),
        ),
    ]
