# Generated by Django 5.0.3 on 2024-03-11 20:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_alter_posts_published_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='img',
            field=models.ImageField(default='/svg/no_image_avaliable.svg', upload_to='photos/%Y/%m/%d/', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='posts',
            name='published_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 11, 23, 6, 42, 526984), verbose_name='Время публикации'),
        ),
    ]
