# Generated by Django 5.0.3 on 2024-03-13 16:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_alter_posts_img_alter_posts_published_time'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='posts',
            options={'ordering': ['published_time'], 'verbose_name': 'Посты', 'verbose_name_plural': 'Посты'},
        ),
        migrations.AlterField(
            model_name='posts',
            name='published_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 13, 19, 22, 55, 791639), verbose_name='Время публикации'),
        ),
    ]
